USE [master]
GO

/****** Object:  Database [RestaurantDB]    Script Date: 2025-03-06 7:50:40 PM ******/
CREATE DATABASE [RestaurantDB] ON  PRIMARY 
( NAME = N'RestaurantDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\RestaurantDB.mdf' , SIZE = 2304KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'RestaurantDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\RestaurantDB_log.LDF' , SIZE = 768KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [RestaurantDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [RestaurantDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [RestaurantDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [RestaurantDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [RestaurantDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [RestaurantDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [RestaurantDB] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [RestaurantDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [RestaurantDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [RestaurantDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [RestaurantDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [RestaurantDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [RestaurantDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [RestaurantDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [RestaurantDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [RestaurantDB] SET  ENABLE_BROKER 
GO

ALTER DATABASE [RestaurantDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [RestaurantDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [RestaurantDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [RestaurantDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [RestaurantDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [RestaurantDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [RestaurantDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [RestaurantDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [RestaurantDB] SET  MULTI_USER 
GO

ALTER DATABASE [RestaurantDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [RestaurantDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [RestaurantDB] SET  READ_WRITE 
GO

